### ISSUE TITLE
Порядок подключения конфигов

### ISSUE THREAD

**Issue by alglyzin** [Jampire/moonshine-impersonate#29]
В конфигурации пакета используются значения из конфига moonshine, но он подключается позже, поэтому значения там null.

- Laravel 11
- MoonShine 2

**Comment by Jampire** [comment]
Laravel 11 пока не поддерживается. Готов рассмотреть ваш PR или добавлю свой позже.

**Comment by Jampire** [comment]
Смотрите комментарий [тут](https://github.com/Jampire/moonshine-impersonate/issues/30#issuecomment-2070372961).
