### ISSUE TITLE
Не переключает обратно

### ISSUE THREAD

**Issue by alglyzin** [Jampire/moonshine-impersonate#30]
Переключение заработало у меня только после того как в конфиг moonshine я добавил middleware:

```
'middlewares' => [
    SecurityHeadersMiddleware::class,
    ImpersonateMiddleware::class,
],
```

Но обратно переключаться он отказывается, кнопка возврата пропадает, а пользователь остается прежний.

Laravel 11
Moonshine 2.10.0

**Comment by Jampire** [comment]
Laravel 11 пока не поддерживается. Готов рассмотреть ваш PR или добавлю свой позже.

**Comment by Jampire** [comment]
@alglyzin Проверено на свежей установке Laravel. Всё работает. Использованный стек:
- php 8.3.6
- Laravel 11.4.0
- Laravel Breeze 2.0.2
- MoonShine 2.11.7
- MoonShine Impersonate 2.0.1

Если у вас по-прежнему не работает, создайте новый issue с детальным описанием проблемы:
- использованный стек (как выше)
- детальный лог ошибок
